on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
      - run: |
          .\gradlew.bat build --no-daemon -i
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports
          path: build/reports
